In [98]:
import pandas as pd
import numpy as np
import math

In [99]:
def pack_size(row):
    if math.isnan(row['pack_size']):
        return float(row['pack_size_text'].split(' ')[0])
    else:
        return row['pack_size']
    
def item_weight(row):
    if math.isnan(row['item_weight']):
        if math.isnan(row['item_density']):
            return float(row['pack_size_text'].split(' ')[3])
        else:
            return row['item_volume'] * row['item_density']    
    else:
        return row['item_weight']
    
def pack_size_text(row):
    if type(row['pack_size_text']) == float:
        return f"{int(row['pack_size'])} packs of {row['item_weight']} kg"
    else:
        return row['pack_size_text']

In [100]:
df = pd.read_csv('ingredient_quantities.csv')

In [101]:
df

,id,pack_size_text,pack_size,item_volume,item_density,item_weight,total_weight
0,1,NaN,20.0,NaN,NaN,3.0,60.0
1,2,5 bottles of 1 kg,5.0,NaN,NaN,1.0,5.0
2,3,NaN,1.0,2.0,0.9,1.8,1.8
3,4,6 boxes of 3 kg,NaN,NaN,NaN,NaN,NaN
4,5,NaN,5.0,3.4,2.0,NaN,NaN
5,6,8 packs of 4 kg,NaN,NaN,NaN,NaN,32.0
6,7,6 boxes of 4 kg,NaN,NaN,NaN,NaN,NaN
7,8,4 boxes of 3 kg,4.0,NaN,NaN,3.0,NaN
8,9,NaN,3.0,NaN,NaN,1.0,NaN
9,10,NaN,2.0,3.0,4.0,NaN,NaN

In [102]:
df['pack_size'] = df.apply(pack_size, axis=1)

In [103]:
df

,id,pack_size_text,pack_size,item_volume,item_density,item_weight,total_weight
0,1,NaN,20.0,NaN,NaN,3.0,60.0
1,2,5 bottles of 1 kg,5.0,NaN,NaN,1.0,5.0
2,3,NaN,1.0,2.0,0.9,1.8,1.8
3,4,6 boxes of 3 kg,6.0,NaN,NaN,NaN,NaN
4,5,NaN,5.0,3.4,2.0,NaN,NaN
5,6,8 packs of 4 kg,8.0,NaN,NaN,NaN,32.0
6,7,6 boxes of 4 kg,6.0,NaN,NaN,NaN,NaN
7,8,4 boxes of 3 kg,4.0,NaN,NaN,3.0,NaN
8,9,NaN,3.0,NaN,NaN,1.0,NaN
9,10,NaN,2.0,3.0,4.0,NaN,NaN

In [104]:
df['item_weight'] = df.apply(item_weight, axis=1)

In [105]:
df

,id,pack_size_text,pack_size,item_volume,item_density,item_weight,total_weight
0,1,NaN,20.0,NaN,NaN,3.0,60.0
1,2,5 bottles of 1 kg,5.0,NaN,NaN,1.0,5.0
2,3,NaN,1.0,2.0,0.9,1.8,1.8
3,4,6 boxes of 3 kg,6.0,NaN,NaN,3.0,NaN
4,5,NaN,5.0,3.4,2.0,6.8,NaN
5,6,8 packs of 4 kg,8.0,NaN,NaN,4.0,32.0
6,7,6 boxes of 4 kg,6.0,NaN,NaN,4.0,NaN
7,8,4 boxes of 3 kg,4.0,NaN,NaN,3.0,NaN
8,9,NaN,3.0,NaN,NaN,1.0,NaN
9,10,NaN,2.0,3.0,4.0,12.0,NaN

In [106]:
df['total_weight'] = df['pack_size'] * df['item_weight']

In [107]:
df

,id,pack_size_text,pack_size,item_volume,item_density,item_weight,total_weight
0,1,NaN,20.0,NaN,NaN,3.0,60.0
1,2,5 bottles of 1 kg,5.0,NaN,NaN,1.0,5.0
2,3,NaN,1.0,2.0,0.9,1.8,1.8
3,4,6 boxes of 3 kg,6.0,NaN,NaN,3.0,18.0
4,5,NaN,5.0,3.4,2.0,6.8,34.0
5,6,8 packs of 4 kg,8.0,NaN,NaN,4.0,32.0
6,7,6 boxes of 4 kg,6.0,NaN,NaN,4.0,24.0
7,8,4 boxes of 3 kg,4.0,NaN,NaN,3.0,12.0
8,9,NaN,3.0,NaN,NaN,1.0,3.0
9,10,NaN,2.0,3.0,4.0,12.0,24.0

In [108]:
df['pack_size_text'] = df.apply(pack_size_text, axis=1)

In [109]:
df

,id,pack_size_text,pack_size,item_volume,item_density,item_weight,total_weight
0,1,20 packs of 3.0 kg,20.0,NaN,NaN,3.0,60.0
1,2,5 bottles of 1 kg,5.0,NaN,NaN,1.0,5.0
2,3,1 packs of 1.8 kg,1.0,2.0,0.9,1.8,1.8
3,4,6 boxes of 3 kg,6.0,NaN,NaN,3.0,18.0
4,5,5 packs of 6.8 kg,5.0,3.4,2.0,6.8,34.0
5,6,8 packs of 4 kg,8.0,NaN,NaN,4.0,32.0
6,7,6 boxes of 4 kg,6.0,NaN,NaN,4.0,24.0
7,8,4 boxes of 3 kg,4.0,NaN,NaN,3.0,12.0
8,9,3 packs of 1.0 kg,3.0,NaN,NaN,1.0,3.0
9,10,2 packs of 12.0 kg,2.0,3.0,4.0,12.0,24.0